  
# This file controls the AWS CodeBuild

version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
  build:
    commands:
    - echo "Entered build phase"
    - mvn clean install
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - ls
    - cd target && ls  
    - cd ..
    - cp target/*.war ./app.war
    - ls
artifacts:
  files:
    - target/simple.war