INSERT INTO `advisor` (`advId`,`name`, `designation`, `emailId`, `password`, `phoneNumber`,`partyStatusId`,`created`,`updated`,`delete_flag`,`advType`) VALUES ('ADV000000000A','adv','Eng','adv@adv.com','!@AS12as','9874563210',1, '2019-03-07 10:58:58', '2019-03-07 10:58:58','N',1);
INSERT INTO `award` (`awardId`,`title`, `issuedBy`, `year`, `imagePath`, `advId`,`delete_flag`) values (1,'Award','IRDA','1998','award.jpg','ADV000000000A', 'N');
INSERT INTO `certificate` (`certificateId`,`title`, `issuedBy`, `year`, `imagePath`, `advId`,`delete_flag`) values (1,'Certificate','IRDA','1999', 'certificate.jpg','ADV000000000A','N');
INSERT INTO `education` (`eduId`,`institution`, `degree`, `field`, `fromYear`, `toYear`, `advId`,`delete_flag`) values (1,'IIT','B.E','IT','MAR-1996','AUG-1998', 'ADV000000000A', 'N');
INSERT INTO `experience` (`expId`,`company`, `designation`, `location`, `fromYear`, `toYear`, `advId`,`delete_flag`) values (1,'sowise','engineer','chennai','JUN-2002','SEP-2004', 'ADV000000000A', 'N');
INSERT INTO `advvideo` (`advId`, `title`, `aboutVideo`,`video`,`delete_flag`) values ('ADV000000000A','advisorVDO','Advisor Videos','adv.mp4','N');
INSERT INTO `advproduct` (`advProdId`,`advId`, `prodId`, `serviceId`,`remId`,`licId`,`delete_flag`,`licImage`,`licNumber`,`validity`) values (1,'ADV000000000A',1,1,1,1,'N','product.jpg','ABC123','12-05-2012');
INSERT INTO `secret_key` (`key`) VALUES('EncryptionKeySowise');
INSERT INTO `advisorType` (`id`,`advType`) VALUES (1,'individual');
INSERT INTO `advisorType` (`id`,`advType`) VALUES (2,'corporate');
INSERT INTO `role` (`id`,`name`) VALUES (1,'advisor');
INSERT INTO `role` (`id`,`name`) VALUES (2,'investor');
INSERT INTO `role` (`id`,`name`) VALUES (3,'admin');
INSERT INTO `product` (`prodId`,`product`) VALUES (3,'Mutual funds');
INSERT INTO `service` (`serviceId`,`service`,`prodId`) VALUES (1,'GoalPlanning',3);
INSERT INTO `brand` (`brandId`,`brand`,`prodId`) VALUES (1,'Aditya Birla Sun Life',3);
INSERT INTO `brand` (`brandId`,`brand`,`prodId`) VALUES (2,'axis',3);
INSERT INTO `advbrandinfo` (`prodId`, `serviceId`,`brandId`, `delete_flag`, `priority`,`advId`) values (1,1,1,'N',1,'ADV000000000A');
INSERT INTO `advbrandinfo` (`prodId`, `serviceId`,`brandId`, `delete_flag`, `priority`,`advId`) values (1,2,2,'N',2,'ADV000000000A');
INSERT INTO `license` (`licId`,`license`,`issuedBy`,`prodId`) VALUES (1,'Certified Financial Planning','FPSB India',1);
INSERT INTO `remuneration` (`remId`,`remuneration`) VALUES (1,'Fee');
INSERT INTO `advbrandrank` (`advBrandRankId`,`advId`,`prodId`,`brandId`,`ranking`,`delete_flag`) VALUES (1,'ADV000000000A',1,1,1,'N');
INSERT INTO `advbrandrank` (`advBrandRankId`,`advId`,`prodId`,`brandId`,`ranking`,`delete_flag`) VALUES (2,'ADV000000000A',2,2,2,'N');
INSERT INTO `category` (`categoryId`,`categoryTypeId`,`desc`) VALUES (1,1,'life insur');
INSERT INTO `category` (`categoryId`,`categoryTypeId`,`desc`) VALUES (2,1,'general insur');
INSERT INTO `categorytype` (`categoryTypeId`,`desc`) VALUES (1,'investment');
INSERT INTO `categorytype` (`categoryTypeId`,`desc`) VALUES (2,'accounting');
INSERT INTO `forumcategory` (`id`,`name`) VALUES (1,'mutual funds');
INSERT INTO `forumcategory` (`id`,`name`) VALUES (2,'stock');
INSERT INTO `riskquestionaire` (`answerId`,`answer`,`question`,`questionId`) VALUES (2,'i dont take risk at all','how would you rate your willingness to take risk','1');
INSERT INTO `goalsserved` (`goalsServedId`,`goalsServed`) VALUES (1,'insure');
INSERT INTO `specialisedskills` (`specialisedSkillId`,`specialisedSkill`) VALUES (1,'goal setting');
INSERT INTO `forumsubcategory` (`id`,`categoryId`,`name`) VALUES (1,1,'equity fund');
INSERT INTO `forumstatus` (`id`,`desc`) VALUES (1,'init');
INSERT INTO `partystatus` (`id`,`desc`) VALUES (1,'active');
INSERT INTO `partystatus` (`id`,`desc`) VALUES (2,'inactive');
INSERT INTO `state` (`stateId`,`state`) VALUES (1,'Andhra Pradesh');
INSERT INTO `city` (`cityId`,`stateId`,`city`,`pincode`) VALUES (1,1,'Achampalle','515621');
INSERT INTO `city` (`cityId`,`stateId`,`city`,`pincode`) VALUES (2,1,'Adaram','517643');
