DROP TABLE IF EXISTS `advisor`;
CREATE TABLE `advisor` (
	`advId` VARCHAR(50) NOT NULL,
	`advType` INT(11) NOT NULL,
	`name` VARCHAR(100) NULL DEFAULT NULL,
	`designation` VARCHAR(100) NULL DEFAULT NULL,
	`emailId` VARCHAR(250) NULL DEFAULT NULL,
	`password` VARCHAR(50) NULL DEFAULT NULL,
	`phoneNumber` VARCHAR(15) NULL DEFAULT NULL,
	`delete_flag` VARCHAR(1) NULL DEFAULT NULL,
	`partyStatusId` BIGINT(1) NULL DEFAULT NULL,
	`created` TIMESTAMP NULL DEFAULT NULL,
	`updated` TIMESTAMP NULL DEFAULT NULL,
	`displayName` VARCHAR(100) NULL DEFAULT NULL,
	`dob` VARCHAR(10) NULL DEFAULT NULL,
	`gender` VARCHAR(1) NULL DEFAULT NULL,
	`panNumber` VARCHAR(10) NULL DEFAULT NULL,
	`address1` VARCHAR(300) NULL DEFAULT NULL,
	`address2` VARCHAR(300) NULL DEFAULT NULL,
	`state` VARCHAR(25) NULL DEFAULT NULL,
	`city` VARCHAR(25) NULL DEFAULT NULL,
	`pincode` VARCHAR(6) NULL DEFAULT NULL,
	`aboutme` VARCHAR(350) NULL DEFAULT NULL,
	PRIMARY KEY (`advId`)
);
DROP TABLE IF EXISTS `secret_key`;
CREATE TABLE `secret_key` (
	`key` VARCHAR(50) NULL DEFAULT NULL
);
DROP TABLE IF EXISTS `advisortype`;
CREATE TABLE `advisortype` (
	`id` INT(11) NULL DEFAULT NULL,
	`advType` VARCHAR(20) NULL DEFAULT NULL
);
DROP TABLE IF EXISTS `role`;
CREATE TABLE `role` (
	`ID` INT(3) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
);
DROP TABLE IF EXISTS `party`;
CREATE TABLE `party` (
	`partyId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`partyStatusId` INT(1) NULL DEFAULT NULL,
	`roleId` INT(3) NULL DEFAULT NULL,
	`roleBasedId` VARCHAR(20) NULL DEFAULT NULL,
	`created` TIMESTAMP NULL DEFAULT NULL,
	`updated` TIMESTAMP NULL DEFAULT NULL,
	`delete_flag` VARCHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`partyId`)
);
DROP TABLE IF EXISTS `award`;
CREATE TABLE `award` (
	`awardId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`imagePath` VARCHAR(350) NULL DEFAULT NULL,
	`issuedBy` VARCHAR(100) NULL DEFAULT NULL,
	`title` VARCHAR(100) NULL DEFAULT NULL,
	`year` VARCHAR(4) NULL DEFAULT NULL,
	`advId` VARCHAR(50) NULL DEFAULT NULL,
	`delete_flag` VARCHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`awardId`)
);
DROP TABLE IF EXISTS `certificate`;
CREATE TABLE `certificate` (
	`certificateId` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`imagePath` VARCHAR(300) NULL DEFAULT NULL,
	`issuedBy` VARCHAR(100) NULL DEFAULT NULL,
	`title` VARCHAR(100) NULL DEFAULT NULL,
	`year` VARCHAR(4) NULL DEFAULT NULL,
	`advId` VARCHAR(20) NULL DEFAULT NULL,
	`delete_flag` VARCHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`certificateId`)
	);
DROP TABLE IF EXISTS `education`;
CREATE TABLE `education` (
	`eduId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`degree` VARCHAR(150) NULL DEFAULT NULL,
	`field` VARCHAR(100) NULL DEFAULT NULL,
	`fromYear` VARCHAR(20) NULL DEFAULT NULL,
	`toYear` VARCHAR(20) NULL DEFAULT NULL,
	`institution` VARCHAR(250) NULL DEFAULT NULL,
	`advId` VARCHAR(50) NULL DEFAULT NULL,
	`imagePath` VARCHAR(350) NULL DEFAULT NULL,
	`delete_flag` VARCHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`eduId`)
);
DROP TABLE IF EXISTS `experience`;
CREATE TABLE `experience` (
	`expId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`company` VARCHAR(200) NULL DEFAULT NULL,
	`designation` VARCHAR(100) NULL DEFAULT NULL,
	`fromYear` VARCHAR(20) NULL DEFAULT NULL,
	`toYear` VARCHAR(20) NULL DEFAULT NULL,
	`location` VARCHAR(100) NULL DEFAULT NULL,
	`advId` VARCHAR(50) NULL DEFAULT NULL,
	`delete_flag` VARCHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`expId`)
);
DROP TABLE IF EXISTS `advvideo`;
CREATE TABLE `advvideo` (
	`videoId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`advId` VARCHAR(50) NULL DEFAULT NULL,
	`title` VARCHAR(100) NULL DEFAULT NULL,
	`aboutVideo` VARCHAR(250) NULL DEFAULT NULL,
	`video` VARCHAR(250) NULL DEFAULT NULL,
	`delete_flag` VARCHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`videoId`)
);
DROP TABLE IF EXISTS `advproduct`;
CREATE TABLE `advproduct` (
	`advProdId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`advId` VARCHAR(20) NULL DEFAULT NULL,
	`prodId` BIGINT(20) NULL DEFAULT NULL,
	`serviceId` BIGINT(20) NULL DEFAULT NULL,
	`remId` BIGINT(20) NULL DEFAULT NULL,
	`licId` BIGINT(20) NULL DEFAULT NULL,
	`delete_flag` VARCHAR(1) NULL DEFAULT NULL,
	`licImage` VARCHAR(350) NULL DEFAULT NULL,
	`licNumber` VARCHAR(50) NULL DEFAULT NULL,
	`validity` VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY (`advProdId`)
	);
DROP TABLE IF EXISTS `product`;
CREATE TABLE `product` (
	`prodId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`product` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`prodId`)
);
DROP TABLE IF EXISTS `service`;
CREATE TABLE `service` (
	`serviceId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`service` VARCHAR(100) NULL DEFAULT NULL,
	`prodId` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`serviceId`)
);
DROP TABLE IF EXISTS `brand`;
CREATE TABLE `brand` (
	`brandId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`brand` VARCHAR(100) NULL DEFAULT NULL,
	`prodId` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`brandId`)
);

DROP TABLE IF EXISTS `advbrandinfo`;
CREATE TABLE `advbrandinfo` (
	`advBrandId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`advId` VARCHAR(20) NULL DEFAULT NULL,
	`prodId` BIGINT(20) NULL DEFAULT NULL,
	`serviceId` BIGINT(20) NULL DEFAULT NULL,
	`brandId` BIGINT(20) NULL DEFAULT NULL,
	`priority` INT(3) NULL DEFAULT NULL,
	`delete_flag` VARCHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`advBrandId`)
);

DROP TABLE IF EXISTS `advbrandrank`;
CREATE TABLE `advbrandrank` (
	`advBrandRankId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`advId` VARCHAR(20) NULL DEFAULT NULL,
	`prodId` BIGINT(20) NULL DEFAULT NULL,
	`brandId` BIGINT(20) NULL DEFAULT NULL,
	`ranking` BIGINT(3) NULL DEFAULT NULL,
	`delete_flag` VARCHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`advBrandRankId`)
);

DROP TABLE IF EXISTS `license`;
CREATE TABLE `license` (
	`licId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`license` VARCHAR(100) NULL DEFAULT NULL,
	`issuedBy` VARCHAR(100) NULL DEFAULT NULL,
	`prodId` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`licId`)
);
DROP TABLE IF EXISTS `remuneration`;
CREATE TABLE `remuneration` (
	`remId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`remuneration` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`remId`)
);

DROP TABLE IF EXISTS `category`;
CREATE TABLE `category` (
	`categoryId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`categoryTypeId` BIGINT(20) NULL DEFAULT NULL,
	`desc` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`categoryId`)
);
DROP TABLE IF EXISTS `categorytype`;
CREATE TABLE `categorytype` (
	`categoryTypeId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`desc` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`categoryTypeId`)
);
DROP TABLE IF EXISTS `forumcategory`;
CREATE TABLE `forumcategory` (
	`id` INT(3) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);
DROP TABLE IF EXISTS `riskquestionaire`;
CREATE TABLE `riskquestionaire` (
	`answerId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`answer` VARCHAR(150) NULL DEFAULT NULL,
	`question` VARCHAR(50) NULL DEFAULT NULL,
	`questionId` VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY (`answerId`)
);
DROP TABLE IF EXISTS `goalsserved`;
CREATE TABLE `goalsserved` (
	`goalsServedId` INT(3) NOT NULL AUTO_INCREMENT,
	`goalsServed` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`goalsServedId`)
);
DROP TABLE IF EXISTS `specialisedskills`;
CREATE TABLE `specialisedskills` (
	`specialisedSkillId` INT(3) NOT NULL AUTO_INCREMENT,
	`specialisedSkill` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`specialisedSkillId`)
);
DROP TABLE IF EXISTS `forumsubcategory`;
CREATE TABLE `forumsubcategory` (
	`id` INT(3) NOT NULL AUTO_INCREMENT,
	`categoryId` INT(3) NULL DEFAULT NULL,
	`name` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);
DROP TABLE IF EXISTS `forumstatus`;
CREATE TABLE `forumstatus` (
	`id` INT(2) NOT NULL AUTO_INCREMENT,
	`desc` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);
DROP TABLE IF EXISTS `partystatus`;
CREATE TABLE `partystatus` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`desc` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);
DROP TABLE IF EXISTS `state`;
CREATE TABLE `state` (
	`stateId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`state` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`stateId`)
);
DROP TABLE IF EXISTS `city`;
CREATE TABLE `city` (
	`cityId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`stateId` BIGINT(20) NULL DEFAULT NULL,
	`city` VARCHAR(50) NULL DEFAULT NULL,
	`pincode` VARCHAR(6) NULL DEFAULT NULL,
	PRIMARY KEY (`cityId`)
);









